### ISSUE TITLE
Difference in display of units of timeseries and temporal rasters in charts

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-client#1112]
A timeseries and (point intersection on) a temporal raster with the same observation_type (e.g. unit = m, reference = AHD) are presented in charts with different units on the Y-axis. This also leads to the problem that when these series are combined in one chart the axis isn't scaled to both series. This way the series can't be compared well.

Preferred unit format = “{unit}{reference}” (so just concatenate the two)

Screenshots:
![image-2020-04-15-09-18-05-786.png](https://images.zenhubusercontent.com/5ede7bc07ba84b329a46dbb0/b0a2d72e-a588-4409-bd6c-4bcbdacc5231)

![image-2020-04-15-09-22-06-802.png](https://images.zenhubusercontent.com/5ede7bc07ba84b329a46dbb0/ea0d6138-b5e7-44c0-b691-260b69b84897)

![image-2020-04-15-09-22-38-513.png](https://images.zenhubusercontent.com/5ede7bc07ba84b329a46dbb0/71f1feba-e462-4dd8-b175-eb19f3ea4a86)

**FOR TESTING:** 

https://nxt3.staging.lizard.net/en/charts/topography,assetgroup$b1d7f43,scenario$07c5c35,raster$ee37e05/point/measuringstation$4733/@-33.7868,150.9797,13/-143Days18Hours-143Days7Hours

**Latest Test from Lex:**

Due to probably a backend issue (water levels of 3Di scenarios do not show any data) this can only be tested partly. However, if I combine the two series in one chart it still doesn’t combine the y-axes. Displayed units are the same but you can still switch them by clicking the y-axis. I don’t expect this has to do with the lack of data points in the temporal raster series.

Is there another mechanism that prevents the combination of timeseries data and a series from a temporal raster? Could you check this?

**Comment by hoanphungt** [comment]
@lexvand 
The problem is although they have the same unit displayed in the y-axis (combination of unit and reference_frame), only unit field is used for the value of y-axis. So the timeseries and temporal raster in the example below have different units indeed (`m` and `mAHD`). So I am changing the y value to also combine the unit and reference_frame (if there is reference_frame available).

Example: https://nxt3.staging.lizard.net/en/charts/topography,assetgroup$b1d7f43,scenario$07c5c35,raster$ee37e05/point/measuringstation$4733/@-33.7868,150.9797,13/-143Days18Hours-143Days7Hours

**Comment by lexvand** [comment]
I still don't fully understand where the difference comes from. If I compare the following endpoints the serialization of observation_type for both timeseries and rasters is the same:
https://nxt3.staging.lizard.net/api/v3/timeseries/c7ab1363-dce5-4702-9c29-10d51feb1d75/
https://nxt3.staging.lizard.net/api/v3/rasters/01456df8-927e-4884-8236-9fb730937b19/

**Comment by hoanphungt** [comment]
@lexvand 

I still can't make it work correctly. The drawing mechanism is quite complicated.

But I figured to configure this observation type https://nxt3.staging.lizard.net/admin/hydra_core/observationtype/495/ (changed unit field from m to mAHD and delete its reference frame field). 

Now if you open the above example again (https://nxt3.staging.lizard.net/en/charts/topography,assetgroup$b1d7f43,scenario$07c5c35,raster$ee37e05/point/measuringstation$4733/@-33.7868,150.9797,13/-143Days18Hours-143Days7Hours) and combine the two graphs. They are now being combined into 1 y-axis only.

However, the problem is if you drag the chart with no data after the other chart, here is the result:
![Screenshot from 2020-06-11 10-35-31.png](https://images.zenhubusercontent.com/5ede7bc07ba84b329a46dbb0/6fb1843f-1f4c-471d-9cca-7f189d9c0fc8)
The chart with no data will remove the data from the other chart. 
I don't know what will happen if we combine 2 charts both with data, maybe in that case, it will scale well together. I cannot find any intersection point with data on both chart

**Comment by lexvand** [comment]
The disappearing graph when one series is empty is an old known issue. Hopefully this is fixed when the backend issue with raster data is resolved. 

Let's wrap up this issue and not try to fix the deeper problems. It is just too complex. Now we know we can arrange it by adjusting the configuration we can make it work.

We keep in mind that we need to handle this better for a future Lizard client. Thanks for the investigation @hoanphungt!

**Comment by hoanphungt** [comment]
@lexvand Ok, so no further action is required for this ticket, isn't it? In that case, I will move it to done.

**Comment by lexvand** [comment]
Indeed, no further action required.
