### ISSUE TITLE
Slow loading tiles Dashboard

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1120]
Hi,

Since a while (multiple weeks to months), the tiles in multiple dashboards load very slowly, up to 30 seconds.
Examples:
https://hunzeenaas.lizard.net/dashboards/boezembeheer
https://parramatta.lizard.net/floodsmart/

- The configurations of these dashboards has not changed
- The tiles with timeseries load the slowest: the tile in 10 -15 seconds, and then the graph itself. The graph loading always took long, but not the tile. 
- If you go to a specific slow loading tile (e.g. https://hunzeenaas.lizard.net/dashboards/boezembeheer/full/11), it goes faster (but still slow).
- The users claim it appeared suddenly (probably beginning of July) 

If you have any suggestions how to improve the loading speed for the overview, please let me know. Also if you need further investigation on something.

Via Martijn Krol (Topdesk 2008 0065) and Jeroen de Koning (Topdesk 2007 0167)
@lexvand

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,
I think I remember that we did an update here recently.
I am a bit busy with all sort of small things, but will have a look at this quickly so we can estimate this, all right?
kr Tom

**Comment by Derryrover** [comment]
We did an update 2020 july 17 as part of ticket:
https://github.com/nens/lizard-tile-dashboard/issues/167
See also changes:
https://github.com/nens/lizard-tile-dashboard/compare/v0.0.59...master
We stopped retrying after url returned error, but this should not make the dashboard slower.

**Comment by Derryrover** [comment]
@remcogerlich 

Hi Remco,

See above. We do keep getting some complaints about the dashboards (tile + parramatta) and their perceived performance.
I have troubleshooted the thing several times now, sometimes with succes sometimes without.
Would it be good if you could have a look at them once more?

I also need to advice if we would like to add features to these apps yes or no.
This becomes a though decision because:
- I do think they are economically viable in terms of features
- But the performance problems keep coming back and are very hard to troubleshoot. I feel frustration from consultants too.

kr Tom

**Comment by Derryrover** [comment]
let us keep a list here of similar problems to get a overview of how recurring this problem is:

**related to performance parramatta:**
https://github.com/nens/parramatta-dashboard/issues/222
https://github.com/nens/parramatta-dashboard/issues/225
https://github.com/nens/parramatta-dashboard/issues/190
https://github.com/nens/lizard-tile-dashboard/issues/167 -> error retry

**Comment by lisannewapstra** [comment]
Thanks for your input Tom. 

@remcogerlich  can you have a look soon?

Jeroen gets complains from customers (HeA and Parramatta). 
@joeriverheijden

**Comment by lisannewapstra** [comment]
@lexvand  Waarom is deze uit de sprint gehaald?

**Comment by Derryrover** [comment]
@lexvand 
@remcogerlich 
@lisannewapstra 

Hi Lex ,Remco, Lisanne

We need to do something with this dashboard performance ticket.
It is clear that we cannot solve this on short term.
But we do need to come with a short term and long term proposal.
Right now we are costing the business a lot of time and frustration and we run the risk of loosing clients (and not land new clients).

@lisannewapstra Could you verify with Jeroen en martijn Krol if we actaully run the risk of loosing customers? What is their feeling about it if we cannot significantly improve?


short term:
@remcogerlich Could we together investigate this? We know some problems with the redux store exist. Can we pinpoint the performance problems on these or is something else going on? I looked several time here, but could really use your help.
We need to have an estimate if refactoring is useful and what it will cost.

long term:
We might choose from:
- keep adding small patches and make amount of tiles on board smaller. Also communicate to customer that performance is what it is.
- find and refactor the root problems
- rebuild from skratch
- phase out and abandon ? Preferably phase out to another product of ours but in worst case to another company.

kr Tom

**Comment by lisannewapstra** [comment]
Hi Tom,
Jeroen gets really frustrated about this as he gets the complains from the customers and the loss of customers is a real threat. A dashboard is meant for a clear and fast overview, and right now we can not deliver that. 

Also, if he does not feel we are working on this, he loses trust and has trouble selling it as well

**Comment by remcogerlich** [comment]
I will spend today on this.

**Comment by remcogerlich** [comment]
As far as I can see, the tiles start drawing when the result of the first timeseries it has to show are in. Before that, there isn't really anything it can draw.

The number of requests it does is really large, and they take a long time.

Right now I don't see what action I can take about this.

**Comment by lisannewapstra** [comment]
@joeriverheijden  As you can see we discuss a lot about this issue but there is no solution yet. If we do not change the code, we have to limit the timeseries, or accept slow performance. Can you make an action plan?

**Comment by lisannewapstra** [comment]
@lex. issue is solved
