### ISSUE TITLE
Open github repo's - We do this so we can deploy easy, but this is actually not a good reason

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1122]
Many of our repositories for clients are open:
- lizard-client
- parramatta
- tile dashboard
- rain report
basically all except for klimaatatlas and 3di-livesite

Although it can be nice to have open source repo's it seems that the only reason we did it is because we want to be able to deploy a github release to the server without the need to authenticate on github. This is not a good reason.

We should investigate if we can:
- while deploying a release from github, do this from a not open source repo while being authenticated. It seems that the server already has a mechanism to download releases from a closed github repo. We should also do this for the clients.
OR
We could choose not to use the release (directly?) from github, but instead release from something like docker harbor (like for 3di) or just the local computer of the user. User could download first release from github and then upload it to the server (for example).

**Comment by Derryrover** [comment]
@remcogerlich 
@lexvand 

Hi Lex,

This is also a recurring problem that we need to tackle.
We might need a backender to investigate this for us

kr Tom

**Comment by lexvand** [comment]
Outdated by monorepo.
