### ISSUE TITLE
Wms layer HHNK does not show map

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1132]
Here a WMS url that does show an image:
https://kaarten.hhnk.nl/arcgis/rest/services/lis/ontsluiting_riooldata_damoexp_FS_openbaar/MapServer/export?dpi=96&transparent=true&format=png32&layers=show%3A242&bbox=508537.7166450124%2C6878603.179824685%2C539380.0575580394%2C6911432.883473123&bboxSR=102100&imageSR=102100&size=807%2C859&f=image

But this is the url used by demo.lizard it does not show an image
https://kaarten.hhnk.nl/arcgis/rest/services/lis/ontsluiting_riooldata_damoexp_FS_openbaar/MapServer/WmsServer?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=GeoDyn%20Eindresultaat%20(242)&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=True&HEIGHT=256&WIDTH=256&ZINDEX=1005&UUID=05e94e5&SLUG=GeoDyn%20Eindresultaat%20(242)&COMPLEXWMSOPTIONS=%5Bobject%20Object%5D&URL=https%3A%2F%2Fkaarten.hhnk.nl%2Farcgis%2Frest%2Fservices%2Flis%2Fontsluiting_riooldata_damoexp_FS_openbaar%2FMapServer%2FWmsServer&GETFEATUREINFOURL=https%3A%2F%2Fkaarten.hhnk.nl%2Farcgis%2Frest%2Fservices%2Flis%2Fontsluiting_riooldata_damoexp_FS_openbaar%2FMapServer%2FWmsServer&SRS=EPSG%3A3857&OPACITY=1&BBOX=469629.1017841229,6848757.734351791,508764.86026613315,6887893.492833804

Here it can be seen in action on demo.lizard:
https://hhnk.lizard.net/nl/map/topography,wmslayer$05e94e5/point/@52.7820,4.9356,9/-2Days0Hours+0Days3Hours
Open the network tab to see the wms network calls.

**Todo:**
Find out which parts of the url used by lizard are not working.
Can we configure the url differently ? Or do we need to make code changes?

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 
@lisannewapstra 

Hi Lex and Joeri,
Got the question from Lisanne why the url in the description did not show wms layer in lizard-client.
I couldnot solve it right away.
What is the priority? Please place in the backlog or sprint accordingly.
kr Tom

**Comment by lexvand** [comment]
@lisannewapstra 
At first glance: According to the docs it seems to use a different set of parameters compared to the services we know (e.g. Geoserver). In that case we should look at whether we can configure it such that the required parameters are already in the URL. Any additional parameters that are added by the client to build up the map requests will probably be ignored. 

What are the options in the map service? Can we make it work through configuration? If not, we can have a look at whether we can make it work with some not too invasive adjustments in the Lizard Client.

**Comment by lisannewapstra** [comment]
I have a few questions to check by @Derryrover  hopefully

- If I load the layer in QGIS, I get an SSL error (see screenshot)
![image](https://user-images.githubusercontent.com/33685743/95339629-8d23c800-08b4-11eb-8e64-066928083a09.png)
If i ignore, it loads perfectly. Could this certificate prevent the showing in Lizard?

- Another Arcgisfeature layer does show up in Lizard, namely https://geoservices.zuid-holland.nl/arcgis/rest/services/Landelijk_gebied/Landelijk_gebied_algemeen/MapServer/WmsServer

A difference found in the documentation (the only I can find so far) is supported query formats.

Natuurnetwerk Nederland
Supported Query Formats: JSON, **AMF**, geoJSON

Geodyn 
Supported Query Formats: JSON, geoJSON

Is AMF used and required?

**Comment by Derryrover** [comment]
@lisannewapstra 

Hi Lisanne,

-> ""If I load the layer in QGIS, I get an SSL error .
If i ignore, it loads perfectly. Could this certificate prevent the showing in Lizard?""

It could be the reason, but I think it is not the reason. 

-> ""Is AMF used and required?""
I do not know the AMF format. I do not think it is required.
I think the problem is just some different query parameters.


@lexvand  Should we investigate this further in our next sprint?

**Comment by lexvand** [comment]
We analyzed the service and found a different endpoint (/export) that works sort of similar but with a slightly different parameterization. Lisanne will ask HHNK whether they can enable the WMSServer endpoint.

**Comment by lexvand** [comment]
@lisannewapstra Any news here? Can we close the issue?

**Comment by lisannewapstra** [comment]
Yes, this can be closed. They changed the configuration at HHNK. However, I think we should specify our requirements and describe the wms management better in the docs. I will take that upon me.
