### ISSUE TITLE
Dependabot -  Do we want to turn it on for client repo's ?

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1134]
Previously Reinout had dependabot create automatic pr's for outdated packages.
For most repo's nobody would merge them so he turned this off.

Anyway, for the clients we have often merged them and it was usefull.
Let us investigate:
- How we can turn them on for specific client repo's.
- For which clients we actually want it. -> preferably newer  clients like catalogue and 3di-livesite

**Comment by lexvand** [comment]
Outdated by monorepo.
