### ISSUE TITLE
[DESIGN] Timeseries - Timeseries

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-client#1146]
Design document:

https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/

- Listview
- Detailed view
- List with explanation box texts

Explanaition in presentation:
https://docs.google.com/presentation/d/1m949-9w-nRHLQT21bwKV7PHYndmtkkbsRzjI0jBB0M4/edit?usp=sharing

**Comment by LirryPinter** [comment]
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/cce5f1b0-c93a-45a8-9a85-d96ba9f56cef)

**Comment by LirryPinter** [comment]
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/8b1f2d1a-5cdc-48a2-9ad3-dc18d81bf022)

**Comment by lexvand** [comment]
@LirryPinter
We went through the design to see if the development issues are complete. Based on https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/, we have the following open ends:
- New item button for timeseries and monitoring network tables
- Interval field --> option for irregular interval (interval = 0)
- Data field in timeseries form --> leave it out for now
- Make supplier/supplier_code fields not read-only
- What does the actions button do in all three forms?
- Modal for location form - select related asset --> set location geometry based on asset geometry
	- What happens if user has filled in geometry and changes related asset, should geometry be updated based on new asset geom?
- Supplier_code is not applicable to locations
- Modal for adding timeseries to monitoring networks
