### ISSUE TITLE
Edit profile link no longer valid

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#1148]
In the user dropdown in the top right corner there is an option to Edit your profile. It links to: http://sso.lizard.net/edit_profile/.

What should we do with this option? Remove it or change to a correct URL?

**Comment by lexvand** [comment]
@caspervdw What are our options here?

**Comment by caspervdw** [comment]
There is no "edit_profile" or "change_password" view in AWS Cognito. It is just not possible for users to do that.

We could implement our own web page that does that based on the AWS API.

But until we do that, edit_profile should not be used anymore.

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-client/pull/1151
merged without review

**Comment by Derryrover** [comment]
v4.18.49 is now on production -> I will deploy to prod right away
