### ISSUE TITLE
Rain report - keeps loading if not authorized

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1150]
If you go to https://apeldoorn.lizard.net/report/rain/ and do no have permission to see the rain raster layer, the client keeps sending requests.
It does not result in an error for the user.

![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/248ffbc7-ec9f-4322-8f5b-cc11309ce945)

Via F12
![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/f0f7e428-235a-4a1e-931e-0dbccf9e01ea)
1 of the requests that ended in 404: https://apeldoorn.lizard.net/api/v3/raster-aggregates/?agg=rrc&geom=POINT+(6.0208082+52.1171791)&rasters=730d6675&srs=EPSG:4326&start=2021-02-01T00:00:00.000Z&stop=2021-02-28T00:00:00.000Z&window=1200000

Please stop the requests after a 404 and show an error message like 'You do not have sufficient permission to view this, please contact servicedesk.. " 

@lexvand

**Comment by Derryrover** [comment]
@lisannewapstra 

Hi Lisanne,

Thank you for reporting this issue.
I seem to have the correct rights with my own user, because I do not experience this issue.
So in order to test this I need to login as a user that does not have the correct rights.
Do you have such a user or could you make it for me?

kr Tom

**Comment by lisannewapstra** [comment]
Hi Tom,
I created a testaccount
If you login do demo.lizard.net first with
username: regenrapportage
password: Regen123

And then go to https://apeldoorn.lizard.net/report/rain/
You should see the issue

**Comment by Derryrover** [comment]
wip pr:
https://github.com/nens/rain_report/pull/40

**Comment by Derryrover** [comment]
Deploying to production 1.6.53
If something goes wrong revert to 1.6.51

**Comment by Derryrover** [comment]
@lisannewapstra 

Hi Lisanne,

I just deployed what I believe is a fix to production:
https://apeldoorn.lizard.net/report/rain/
Ready for testing. If anything blocking is wrong please let me know and I will revert to previous version.

kr Tom

**Comment by lisannewapstra** [comment]
Looks good, both with and without rights.
