### ISSUE TITLE
Error legend Lizard client - "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1152]
**Topdesk 2102 0093 Legenda hittestress werkt niet**

![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/a8e20ac4-88c5-4643-91cb-5f7ed6dc231b)

The legend used is this:  https://demo.lizard.net/api/v3/colormaps/heat-klimaat/
and in the management screen
![image.png](https://images.zenhubusercontent.com/5ef5e8f83e5d5435204918ce/04e6de64-819d-441d-96b6-2f7963139b1f)

Why doesn't it show in the client?

F12/console gives the following error:
"TypeError: Cannot read property 'length' of undefined"

Lizard link to reproduce: https://demo.lizard.net/nl/map/topography,raster$9109866,raster$6009156/point/@52.1874,5.2625,7/-2Days0Hours+0Days3Hours

@lexvand

**Comment by lexvand** [comment]
Config issue. The observation type was of scale Ordinal. Should be Interval.
