### ISSUE TITLE
Alphabetically order list of timeseries related to Assets

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-client#1153]
FEEDBACK FROM MUNICIPALITY OF UTRECHT: 
Selecting measurements (timeseries) carried out on e.g. pumping stations is currently quite a hassle in Lizard Portal. Especially when a lot measurements are in the list. The main reason is that the measurements are listed in a for the user non-logical way and that the code attribute of the _location_ is shown in the list. 

Removing the "code" attribute and listing the measurements alphabetically would enormously increase the speed at which users can click and find their preferred measurements. 

EXAMPLES:

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/b49f63ae-ea1f-4361-a61c-db2c3144d639)   

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/160e84d8-dac6-487e-a405-41b38f492c56)

**Comment by joeriverheijden** [comment]
@lexvand kan je deze inplannen? Ik hoor het graag als er zaken zijn die niet mogelijk zijn!

**Comment by lexvand** [comment]
Applying alphabetical ordering is good, removing the "code" **is not**. This is the location__name, which is for a lot of timeseries an important unique constraint. We may reconsider the way we present this in a new client.

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

Hi 
If I understand correct I must keep the 'code'.
I will first order alphabetically on code, and for list-items where code is the same I will order on 'name' afterwards.
Is this correct? Or should I not order on code initially?

Also I cannot find this screenshot, maybe could you share a hyperlink?
Further I just requested via topdesk acces to the utrecht organisation in order to see their data.

kr Tom

**Comment by lexvand** [comment]
It's not the code that is presented, it's the location name (which is sometimes the same as the code, but anyways...).

I guess it is easiest to order on the complete string (combination of location name and observation type parameter). If you are able to sort on these names separately, then it is preferred to order primarily on location name and secondarily on observation type parameter.

Other examples of assets with multiple timeseries on staging:
https://nxt3.staging.lizard.net/en/map/topography,assetgroup$b1d7f43/point/measuringstation$1236/@52.0472,5.2226,11/-2Days0Hours+0Days3Hours
https://nxt3.staging.lizard.net/en/map/topography,assetgroup$b1d7f43/point/pumpstation$25484/@52.9185,4.7897,13/-2Days0Hours+0Days3Hours

**Comment by Derryrover** [comment]
solved in pr:
https://github.com/nens/lizard-client/pull/1156
waiting for travis checks.

**Comment by lexvand** [comment]
This is indeed a nice improvement. Can be released to production.

**Comment by joeriverheijden** [comment]
Yes it is:-)

**Comment by Derryrover** [comment]
deployed to prod in 4.18.52
