### ISSUE TITLE
Remove &/ from url WMS request

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1158]
**Topdesk 2103 0070 Enhancement for Lizard WMS Management Interface - Evert&Joeri**

 als ik de GetFeatureInfo url invul als: https://service.pdok.nl/bzk/brogmwkenset/wms/v2_1 **?**

dan maakt Lizard er het volgende van:

https://service.pdok.nl/bzk/brogmwkenset/wms/v2_1 **&/** ?&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&INFO_FORMAT=application/json&LAYERS=gmw_kenset&QUERY_LAYERS=gmw_kenset&STYLES=&SRS=EPSG:4326&BBOX=5.1340484619140625,52.09890343474638,5.139954686164856,52.102096527793414&WIDTH=1101&HEIGHT=969&X=599&Y=419

Die dikgedrukte **&/** zorgt ervoor dat de request niet goed wordt afgehandeld bij de WMS service. Zonder de **&/** in het begin gaat het wel goed.

Kunnen jullie ervoor zorgen dat deze **&/** niet meer wordt toegevoegd in de URL zodat het WMS request goed aankomt bij de service?

**Comment by lexvand** [comment]
I checked and I see slightly different behavior. The standard addition to the GetFeatureInfoURL is "/?&SERVICE=WMS&REQUEST=...".

This means it should work if "https://service.pdok.nl/bzk/brogmwkenset/wms/v2_1" was the correct base URL. However, When I open the [complete URL](https://service.pdok.nl/bzk/brogmwkenset/wms/v2_1/?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&INFO_FORMAT=application/json&LAYERS=gmw_kenset&QUERY_LAYERS=gmw_kenset&STYLES=&SRS=EPSG:4326&BBOX=5.1340484619140625,52.09890343474638,5.139954686164856,52.102096527793414&WIDTH=1101&HEIGHT=969&X=599&Y=419) I get a 404 (or 500 with Lizard proxy in between). That means the base URL is incorrect or some authentication is expected.

@lisannewapstra Can you let Evert know and ask for another analysis on their side?

**Comment by lexvand** [comment]
@Derryrover I've been able to reproduce the issue. It requires a very small change for which I made a PR. I checked if it breaks any existing implementation (98% geoserver layers and some other services) and it doesn't. And even if it does it is easy to fix in the configuration.

Can you make a release for this? Can go directly to prod.

**Comment by Derryrover** [comment]
Deployed v4.18.56 to production and staging
