### ISSUE TITLE
Timeseries not coupled correctly to filters in omnibox

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1162]
**Topdesk 2103 0112 Koppeling tijdreeksen in portaal - Karl Schütt**

Utrecht has a groundwaterstation (346) with 2 filters: 346-1 and 346-2. Both filters have timeseries. 
This works fine in the [API](https://utrecht.lizard.net/api/v3/groundwaterstations/83444/), and in the [Lizard client graph view](https://utrecht.lizard.net/nl/charts/topography,assetgroup$9c2d7b6,assetgroup$b338f61,assetgroup$46f32c4,wmslayer$346544d/point/groundwaterstation$83444+filter$121938+filter$121937/@0.1758,0.0000,2/Sep,28,2009-Feb,04,2020)
![image](https://user-images.githubusercontent.com/33685743/111189057-fcb18800-85b5-11eb-9262-1b5df2b26cdb.png)

In the omnibox however, you can only select the timeseries of the 1st filter.

**Omnibox Filter 1**

![image](https://user-images.githubusercontent.com/33685743/111189114-0cc96780-85b6-11eb-852a-0b4ceef340ba.png)

**Omnibox Filter 2**

![image](https://user-images.githubusercontent.com/33685743/111189167-1c48b080-85b6-11eb-8b04-3d980afec33b.png)

When selecting filter 2, you should see timeseries 346-2, handpeiling etc- . Now you see only 346-1.
A refresh is not the answer, in that case filter 1 is selected again. 

@lexvand  @joeriverheijden

**Comment by lexvand** [comment]
Unfortunately, probably a result of #1153

**Comment by Derryrover** [comment]
@lisannewapstra 

Hi Lisanne,

I have not yet acces to the assets described in the ticket.
Could you grant me acces?

kind regards Tom

**Comment by lisannewapstra** [comment]
Hi Tom, the example is from Utrecht. I sent you an invite with reading rights to Utrecht.

**Comment by lexvand** [comment]
@Derryrover Issue with multiple nested assets is fixed. That's nice.

There is just one small inconsistency: The selected timeseries isn't always the first one in the list. This happens not just for nested assets. I haven't noticed this in the previous test round, so I guess it is introduced by this fix.

Can you fix this and make sure the top entry is always selected by default?

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,
Do not understand this one yet.
Could you give some more details or make a video call?

kr Tom

**Comment by lexvand** [comment]
@Derryrover It works according to how we like to see it now. Go ahead with prod release.

**Comment by Derryrover** [comment]
dic prod deploy from 4.18.52 to 4.18.55
