### ISSUE TITLE
Mapbox background map language Dutch?

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1168]
Comment from Carsten on slack:

Het valt me op dat demo.lizard.net een Engelse kaart geeft (The Hague i.p.v. Den Haag). Aangezien requests rechtstreeks naar mapbox gaan, lijkt me dit geen backend instelling. Mapbox kijkt blijkbaar niet naar HTTP_ACCEPT_LANGUAGE, maar levert ons Engelse strings. Kunnen jullie hierover controle uitoefenen?

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 
Iets om op te pakken Ja / Nee?

**Comment by joeriverheijden** [comment]
Ja lijkt me goed!

**Comment by lexvand** [comment]
@Derryrover Kun je dit een inschatting geven?

**Comment by lexvand** [comment]
Outdated.
