### ISSUE TITLE
Bug with lizard client favourites after landing page change

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1174]
See this comment:
https://github.com/nens/lizard-nxt/issues/5012#issuecomment-884935448

**Comment by RonaldWillemsen** [comment]
Could you also make an indication how likely it is other features are impacted also?
Does the test needs to be redone, or do you feel this is minor

**Comment by Derryrover** [comment]
I think tests need to be redone.
We made significant changes to nginx.

Looking back now I should on staging have disabled the demo.lizard.net url earlier.
Since I didnot do this we didnot find this bug yet (the old url was still used somehow).

The urls of the favorites do not work at /favourites because they should instead be /viewer/favourites.
Anyway /viewer/favourites does also not work so we need to at least make 2 fixes:

- migrate the favourites to become /viewer/favourites
- change something in the lizard-client code to make /viewer/favourites urls work?

**Comment by Derryrover** [comment]
Only did lizard-client changes to fix this.
No nginx changes done.
Seems no migration of favourites is needed because backend just stores uuids of favourites (no urls are stored)

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-client/releases/tag/v4.18.61

**Comment by lexvand** [comment]
The fix works, favourites can be opened again. On staging I ran into some favourites with `"context": "dashboard"`, which needed to be changed to `"context": "charts"` for them to work.
