### ISSUE TITLE
Navigate back from lizard-client to Landing-page

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1176]
I think there is currently no way to do this.

- If the user was just coming from the landing page, then the user can use the browser 'back' button.
- One option would be to configure a "app" in the apps-menu to navigate to lizard.net
We could also always show this, so there is no need to configure for all users?
- We could also add another link at some place to navigate back.

**Comment by Derryrover** [comment]
@Wolfensteijn 
@joeriverheijden 

Made this ticket to navigate from viewer back to landing page
Joeri, would adding the back button to the "apps" be acceptable? (see description).

**Comment by lexvand** [comment]
Duplicate of #1177
