### ISSUE TITLE
Home button in lizard-client, lizard-catalog and management-client

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1177]
We need a different type of home button to go back from the rest of our apps to the landing page.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
I could not yet find the "home" button as discussed in this retro in the design of the landing page.
Could you update the design so it includes this button?
https://github.com/nens/design-tasks/issues/10

kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
You came with feedback regarding the home button last time.
Could you have a look at this ticket?
See previous comment
kr Tom

**Comment by Derryrover** [comment]
Lirry heeft design geupdate.
Knop moet ook op catalog en lizard-client

**Comment by RonaldWillemsen** [comment]
The Lizard Logo works on different pages in different ways.

- In the Lizard Catalogue, if I click the Lizard Logo it redirects me to the Lizard Catalogue

- In the Management environment, if I click the Lizard Logo it redirects me to the Lizard landingspage

I know the delivered item is the home functionality but people use a lot of different ways to navigate, clicking the logo is a common way to navigate to Home.

**Comment by RonaldWillemsen** [comment]
In the management section there is also a third home option. 
I understand it's used to navigate in the Management, but on the homepage it has a different usage, which might be confusing.

![image.png](https://images.zenhubusercontent.com/60d2e391ade8db8d3edd71ef/84da638b-b08e-4306-8fdd-89cf995f0fb0)

Here it directs the user back to the homepage, in the rest of the management domain, it redirects to the previous screen. (which is kinda the same, but not really)

**Comment by RonaldWillemsen** [comment]
In documentation there is an home icon which looks realy the same as all the other home icons, however it has a different function.

It can be confusing for users to use almost identical icons, with different outcomes

![image.png](https://images.zenhubusercontent.com/60d2e391ade8db8d3edd71ef/3518e30b-65ad-4ad4-8791-4e455f00cd09)

**Comment by RonaldWillemsen** [comment]
Suggested improvement: Every tile which does not have a home function, to be opened in a new tab for user experience.

**Comment by lexvand** [comment]
@Derryrover I agree with Ronald about removing the "Go back" tile in the main management page. Can you make that change in order to wrap up this issue?

**Comment by lexvand** [comment]
Excellent work! It all works consistently now.
