### ISSUE TITLE
Some unnecessary arrows when loading a charts favourite

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#1178]
On staging: When I load a charts favourite (with state containing: `{"context": "charts"}`) I see some weird arrows drawn in the left side bar. When you click on them they fold up an empty box in the bar and the arrows disappear. It happens with both older favourites and newly generated ones.

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/a36378fd-fcbc-49ff-aba0-6f025cf95ab2)

On production this doesn't happen.

**Comment by Derryrover** [comment]
Do not understand why this does not work.
Is also broken on master, but seems okey on production on v4.18.56
Going to test v4.18.56 locally

**Comment by Derryrover** [comment]
Locally v4.18.56 was also broken...
There seems to be no change in packages:
https://github.com/nens/lizard-client/compare/v4.18.56...tom-change_homepage
(but can we know for sure? are they pinned correctly?)
Investigate this? -> no: out of scope

Fix: changed this:
<i ng-if="extended"
           ng-click="toggleExtended()"
           class="fa fa-arrow-circle-up"
           title="{{ 'Show less' | translate }}"/>

Intoo:
<i ng-if="extended"
           ng-click="toggleExtended()"
           class="fa fa-arrow-circle-up"
           title="{{ 'Show less' | translate }}"></i>
(zie closing tag)

Now works on dev
https://github.com/nens/lizard-client/pull/117

**Comment by Derryrover** [comment]
merged without review
release here from feature branch "tom-change_homepage"
https://github.com/nens/lizard-client/releases/tag/v4.18.62

test here:
https://nxt3.staging.lizard.net/viewer/en/charts/topography,assetgroup$b1d7f43/multi-point/measuringstation$1253+measuringstation$1255+measuringstation$1256/@0.1758,0.0000,2/Dec,08,2017-Jan,08,2018

**Comment by lexvand** [comment]
Fixed on staging.
