### ISSUE TITLE
Url from klimaatatlas doesnot work

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1181]
This might be an issue with how the url is build up in klimaatatlas.

**Steps to reproduce**

- Go to klimaatatlas almere: https://almere.klimaatatlas.net/

- Open tile landgebruik

- Klick on button "Bekijk in site"

- You will redirect to the following lizard-client url
https://flevoland.lizard.net/viewer/nl/map/landuse_fun,topography/point@52.3633,5.2051,12/-2Days0Hours

- A blank screen will show. This error in console:
Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by Derryrover** [comment]
The following url does work:
https://flevoland.lizard.net/viewer/nl/map/topography/point@52.3633,5.2051,12/-2Days0Hours+0Days3Hours

Note the:
+0Days3Hours
removal of "landuse_fun,"

**Comment by lexvand** [comment]
Indeed a configuration matter.

@Derryrover Did someone report this or did you find it yourself? If it was reported, please inform that person. You could redirect to Remo if there are more questions about this.
