### ISSUE TITLE
Lizard Viewer goes to world view instead configured zoom level & other favourite settings

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1183]
**2110 0016 Bas Nelemans Provincie Noord-Brabant**

Some users do not zoom to the configured zoom level when they open the viewer, but see everything in world view.
- Also the standard layers are not visible
- And the language is English instead of Dutch

In short, the favourite settings are ignored

For grondwaterstand.brabant.nl/viewer, it should go to Brabant, like this:
![image](https://user-images.githubusercontent.com/33685743/137126254-fb695723-c36e-4108-ae39-0ce31ece94cd.png)
url= https://grondwaterstand.brabant.nl/viewer/nl/map/topography,assetgroup$be1ef6a,wmslayer$42a9f70/point/@51.5269,5.1191,10/-2Days0Hours+0Days3Hours
But some users get:
![image](https://user-images.githubusercontent.com/33685743/137128209-e30d034c-5d71-403f-ae96-e5bab325d8dc.png)
url= https://grondwaterstand.brabant.nl/viewer/en/map/topography/point/@0.1758,0.0000,2/-2Days0Hours+0Days3Hours

Found by application management:
- Both logged in and not logged in users
- I (Lisanne) do not have this problem. However, I see this 'wrong' page for a brief moment, and then it loads the favourite correctly. 
- Settings in the admin are correct: https://demo.lizard.net/admin/lizard_nxt/portal/61/change/
- Chrome browser

Also reported earlier by HHNK via Thomas for hhnk.lizard.net. It seems portal independent.

What can be done?
@lexvand @joeriverheijden

**Comment by lexvand** [comment]
Earlier attempts to fix this have been unsuccessful (see: #1154). We decided not to put in any more effort.

**Comment by lisannewapstra** [comment]
Can you please reconsider and discuss with Joeri? It is not only the mapextent, so this ticket has a broader scope.

**Comment by lexvand** [comment]
Outdated, as the old Viewer almost reached end of life.
