### ISSUE TITLE
New lizard-client: Leaflet, Mapbox, Cesium other?

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1195]
For the new Lizard client we need to decie which map library to use.

There are several factors involved:

- Rain / waterdepth result animation:
https://github.com/nens/frontend-tasks/issues/56

- vector tiles / points polygon lines on the map

- cool webGL animations

- 3d views

We therefore list pro's and cons per library below:

Leaflet:
Pro
Con

MapboxGLJS
Pro
Con

Cesium
Pro
Con

Other?

**Comment by gijs** [comment]
See https://github.com/nens/frontend-tasks/issues/57
