### ISSUE TITLE
Replace 3Di logo in search results "Add data layer"

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#1199]
Scenarios are no longer dedicated to 3Di results. They can now be filled with raster results from any modelling software package. In the Viewer we show a 3Di logo in the search results in the data menu. We should replace this by the icon we use in the Management client.

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/0e37d11a-3f2d-48f8-8e02-0d7540b8aa34)

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/9e506317-e6ba-4ec4-b26c-ab8d690ed76c)

**Comment by hoanphungt** [comment]
@lexvand @gijs 
FYI

First attempt to upload the new scenario icon to the lizard-iconfont repo but it's more complicated than just imported directly to the repo. Also, the recent failed update of lizard-iconfont to fantasticon means I need to make a 1.3.x branch in order for it to be released by the backend.

According to Carsten:

> I think we have a problem. Gijs recently updated lizard-iconfont and based it on fantasticon. I made a 2.0.0 and a 2.0.1 release but we encountered problems when used in Lizard that we were not able to solve. See here: https://github.com/nens/lizard-nxt/issues/5357. We decided to downgrade the version of lizard-iconfont used in Lizard to 1.3.7: https://github.com/nens/lizard-nxt/blob/master/package.json#L31.
> 
> So, I see 2 options:
> 
> 1. We merge your pull request to master and we try to solve the problem(s).
> 
> 2. We make a separate 1.3.x branch and continue to work with the "old" version of lizard-iconfont.

So I chose another option which is to not use lizard-iconfont but import the icon directly to the lizard-client repo.

**Comment by lexvand** [comment]
Tested on staging. Looks good. Other icons still work.
