### ISSUE TITLE
Result name of non-3Di scenario results are not being presented

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#1200]
Users can now register their own scenarios and raster results, with names and codes that are not restricted by the options in the 3Di postprocessing. When adding such a scenario to the data menu, the names of the related raster layers are not generated in the menu. Instead it shows 'raster#{short_uuid}'.

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/717c4cad-813a-42e1-91e3-0a3192832079)

When the layer is activated, the name does show up:

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/d90cefe7-c63b-4ad0-a2d2-96160515e7f0)

I suspect that there is a translation module in place that only covers the names of standard 3Di result layers. It should also work for deviating names.

The name is available in the API response when adding the scenario to the menu: https://demo.lizard.net/api/v3/scenarios/51263a5/ (result_set>result_type>name).

**Comment by hoanphungt** [comment]
Ah I probably made a mistake here. You probably want to show result type name, not raster name. The example that you show where the name does appear, it is actually the raster name, not the result type name. That's why there is a confusion here.

**Comment by hoanphungt** [comment]
And there is a translation mechanism here based on the result_type.code and that's why it broke for new result type that is not in the dictionary.

**Comment by lexvand** [comment]
That's correct. It didn't even occur to me that it took the raster name instead. We want it to be the result_type__name. (FYI: Which is actually the name of the Result, as it is filled in in the management screens. The `Result type` model has been removed and partly migrated to `Results`.)

**Comment by hoanphungt** [comment]
Used result_type__name instead of raster name in case of non standard 3Di results. Deployed to staging.

**Comment by lexvand** [comment]
Tested on staging. All looking good.

**Comment by hoanphungt** [comment]
Deployed to production
