### ISSUE TITLE
Wrong translation of shape and material codes

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-client#560]
Zojuist heb ik het rioolstelsel van de gemeente Noordoostpolder opnieuw ingeladen. Bij het bekijken van het resultaat (https://demo.lizard.net/nl/map/waterchain,topography/point/52.7106,5.7278@52.7102,5.7295,17/Jan,30,2016-Feb,13,2016) zie ik dat alle vormen en materialen van putten en leidingen op "afwijkend" staan. Dit heb ik ooit hier (https://github.com/nens/lizard-client/blob/master/app/lizard-nxt-filters.js) in toegevoegd. 

Wat gaat er fout?

**Comment by arjenvrielink** [comment]
verplaatst naar nxt issue list: https://github.com/nens/lizard-nxt/issues/1506
