### ISSUE TITLE
Missing styles query parameter

### ISSUE THREAD

**Issue by byrman** [nens/lizard-client#704]
https://sentry.lizard.net/NenS/lizard-nxt-staging/group/439295/

Deze foutmeldingen zijn als volgt te reproduceren:
- Kies landgebruik
- Kies punt-selectie
- Klik op de kaart

Een request als deze:

https://nxt.staging.lizard.net/api/v2/raster-aggregates/?agg=counts&geom=POINT+(5.072250366210937+52.31897292691066)&rasters=717478e&srs=EPSG:4326&start=2016-08-15T22:00:00&stop=2016-08-17T22:00:00&window=3600000

faalt dan met:

{
status: 500,
message: "Technical error. #500.13",
code: 13,
detail: "'NoneType' object has no attribute 'split'"
}

Wat er ontbreekt in de bovenstaande request is een 'styles' parameter. Dit moet de naam van een colormap zijn. Maar niet zomaar een colormap: eentje die discreet is en met labels. Bijvoorbeeld "styles=lc-fun" toevoegen en ik krijg opeens antwoord (maar styles=autumn werkt bijv. niet).

```
{
  data: [
    {
      color: "#b9ff98",
      data: "1",
      label: "BRP/Top10 - Gras"
    }
  ]
}
```

De vraag is: wat moet er voor styles ingevuld worden? Op dit punt heeft options helemaal geen styles:

https://github.com/nens/lizard-client/blob/master/app/lib/raster-service.js#L57

Moet ik er dan maar een uit mijn duim zuigen?

**Comment by byrman** [comment]
Fixed by https://github.com/nens/lizard-client/commit/dab5aa567ca15ee01274ed30fa17dffe5f12c89d

**Comment by byrman** [comment]
Het toevoegen van de styles parameter lost dit probleem op, maar veroorzaakt een ander probleem: lege grafieken.

![image](https://cloud.githubusercontent.com/assets/1039433/19112353/b0156da0-8b04-11e6-808e-e779303282dc.png)

Deze requests falen nu:

https://nxt.staging.lizard.net/api/v2/raster-aggregates/?agg=curve&geom=POLYGON+((4.163818359375+51.1190409225206,+4.163818359375+52.767877445040874,+6.7730712890625+52.767877445040874,+6.7730712890625+51.1190409225206,+4.163818359375+51.1190409225206))&rasters=e9ed572&srs=EPSG:4326&start=2016-08-15T22:00:00&stop=2016-08-17T22:00:00&styles=dem_nl&window=3600000

https://nxt.staging.lizard.net/api/v2/raster-aggregates/?agg=curve&geom=POLYGON+((4.163818359375+51.1190409225206,+4.163818359375+52.767877445040874,+6.7730712890625+52.767877445040874,+6.7730712890625+51.1190409225206,+4.163818359375+51.1190409225206))&rasters=9c2aabd&srs=EPSG:4326&start=2016-08-15T22:00:00&stop=2016-08-17T22:00:00&styles=dem-world&window=3600000

Verwijder de `styles` query parameter en bovenstaande requests doen het weer.

**Comment by byrman** [comment]
Aangezien het tweede probleem (een front-end die het niet doet) erger is dan het eerste probleem (vervuiling van Sentry), draai ik een deel van mijn eerdere pull request terug.

**Comment by RoelvandenBerg** [comment]
@byrman is dit nog een open issue? Zo ja, dan zou het goed zijn dit te verplaatsen naar de lizard-nxt issues.

**Comment by lexvand** [comment]
Out of date
