### ISSUE TITLE
Point having a z-coordinate causes trouble

### ISSUE THREAD

**Issue by byrman** [nens/lizard-client#705]
https://sentry.lizard.net/NenS/lizard-nxt-staging/group/439781/

https://nxt.staging.lizard.net/api/v2/raster-aggregates/?agg=counts&geom=POINT+(6.30588945123787+52.06170838320384+0)&rasters=717478e&srs=EPSG:4326&start=2016-08-15T22:00:00&stop=2016-08-17T22:00:00&window=3600000

The point has a z-coordinate: (6.30588945123787+52.06170838320384+0). Rastersmurf doesn't like this.

This sends a point without z-coordinate:

![screenshot from 2016-10-04 15 07 47](https://cloud.githubusercontent.com/assets/1039433/19075326/bcd1d68e-8a44-11e6-8ef4-2a5ac0147282.png)

This sends a point with z-coordinate:

![screenshot from 2016-10-04 15 08 03](https://cloud.githubusercontent.com/assets/1039433/19075330/c1af5898-8a44-11e6-8548-7f19fdeab78f.png)

**Comment by byrman** [comment]
Hier de z eraf slopen:

https://github.com/nens/raster-store/blob/master/raster_store/interfaces.py#L84.

Of anders hier:

https://github.com/nens/lizard-nxt/blob/master/lizard_nxt/utils/raster.py#L121

**Comment by arjanverkerk** [comment]
Laten we dat ook maar in de raster-store doen. ogr.Geometry.FlattenTo2D() does the trick. Ik zal er naar kijken.

**Comment by RoelvandenBerg** [comment]
@arjanverkerk  / @byrman is dit nog een open issue? Zo ja, dan zou het goed zijn dit te verplaatsen naar de lizard-nxt issues.
