### ISSUE TITLE
[RFC] Modernization effort

### ISSUE THREAD

**Issue by gijs** [nens/lizard-client#753]
**Top 3 actions** for lizard-client to be picked up in Q1 '17:

1) Move from Bower+Grunt to npm+yarn+webpack
2) Bump versions of essential packages such as D3, Leaflet, etc
3) Move from ES5 to ES6, esp. because of import/export

----------------------------
**Unprioritized list**

This is a quick and incomplete list of possible technical improvements for the lizard-client.

The intention is to start some conversation amongst front-end developers* regarding the technical direction of the product.

- Advance codebase to adopt a **modular code style using ES6** import/export.

- Migrate [away](https://github.com/yarnpkg/yarn/pull/1441) from **bower to npm**.

- Use **npm/webpack for all build processes** including release scripts and i18n via Transifex.

- Use [**Yarn**](https://yarnpkg.com/) instead of `npm install` because this is a saner approach to npm dependency management.

- Switch from Grunt to **Webpack** for bundling, preferably with HMR for dev mode to ease and speed up development of UIs. 

- **Bump versions** of essential packages such as D3, lodash, Leaflet.

- Investigate using a **component-based UI library** like [Vue.js](https://vuejs.org/) or [React](https://facebook.github.io/react/). One advantage of using cleanly componentized code is the ability to re-use them in other places, package them as npm modules, and to add easy-to-reason-about structure to the codebase. This allows us to really separate ie. the omnibox and the timeline into standalone components, installable via npm. It also simplifies testing, as components are functional blocks with predictable input and output.

- Investigate using [**css-modules**](https://github.com/css-modules/css-modules) / local scoped CSS ([more](https://css-modules.github.io/webpack-demo/))

- Decide on **updating to Bootstrap 4** using SCSS via @import instead of writing `!important` overwrites everywhere. This implies switching grid systems etc. 

- Investigate using a **state management** framework like [Redux](http://redux.js.org/), [MobX](https://github.com/mobxjs/mobx) or [Jumpsuit](https://github.com/jumpsuit/jumpsuit/). Keeping state central [has several advantages](http://redux.js.org/docs/introduction/ThreePrinciples.html).

- Investigate using [Relay](https://facebook.github.io/relay/) or a similar data fetching framework. This involves setting up a [GraphQL](http://graphql.org/learn/) endpoint. Perhaps luckily there's [Graphene](http://graphene-python.org/) for Python w/ Django integration, but this will require modification to be able to integrate with our SSO/authn/authz solution. One major early adopter of this tech is Github: [http://githubengineering.com/the-github-graphql-api/](http://githubengineering.com/the-github-graphql-api/). Try it out [here](https://developer.github.com/early-access/graphql/guides/accessing-graphql/).

  - Relay/GraphQL is basically an improvement over REST, where the client specifies what it needs back from the server to render. This request is fulfilled with one tailored response. This saves lots of http requests, prevents over- and underfetching and makes the clientside codebase easier (ie. less promise-xhr-chains needed because all data is right there in the response).

  - As good as this looks and works, it's a lot of work to switch from REST to GraphQL. A good starting point would be to try setting up a GraphQL endpoint parallel to the REST API, and let the developers get used to the concept.

  - The jury is still out on if/how to combine Relay (colocated queries for datafetching per component) and Redux (state mgmt). Also not sure [which](https://github.com/facebook/relay) [lib](https://github.com/apollostack/apollo-client) to use. [This](http://dev.apollodata.com/react/redux.html) looks interesting though.

- Investigate moving to [Jest](https://facebook.github.io/jest/) for [**clientside testing using the snapshot feature**](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html). This will be easy to set up once we switch to a truly componentized architecture.

- Investigate using a **clientside routing** solution such as [React Router](https://github.com/ReactTraining/react-router) or similar.

Anything I forgot? 

What would you like to prioritize?

What's your opinion?

* @d-weeteling @ernstkui @RoelvandenBerg

**Comment by ernstkui** [comment]
Nice! I am convinced of the necessity to modernize the infrastructure of lizard-client. I feel like your bullets are already kind of ordered from no-brainer/easier to debatable/complex. Do you agree? 

I believe moving to webpack would be a great start, and to do this we need to take some other steps which also have value in itself. There are also some steps in the list which seem very hard to me now. But I suggest discussing follow-up steps after we have taken some important and clear steps first.

A good approach could be to order this list, pick the first three and turn those into Trello tickets in the backlog. Implement those tickets in Q1, evaluate and start over. I will make sure we reserve time for this in Q1 if you make sure we have well described tickets.

**Comment by gijs** [comment]
Good to know there will be room for improvement. 

I fully agree: I wanted to start the list with the easier improvements and end with the heavier stuff.

I'll reorder the list with 'top-3-in-Q1' in mind. Creating Trello tickets will come after that. Others: feel free to pitch in.

**Comment by gijs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Lizard Frontend] Upgrade path](https://trello.com/c/ExMq0o48/1162-lizard-frontend-upgrade-path)

**Comment by lexvand** [comment]
Out of date
