### ISSUE TITLE
Backend freezes when successive API calls are being made too fast

### ISSUE THREAD

**Issue by d-weeteling** [nens/lizard-client#755]
When panning/zooming excessively, the backend freezes and API calls remain unanswered:

![screenshot](https://cloud.githubusercontent.com/assets/7764718/20598944/d45ba5e4-b24b-11e6-9a5f-ae70f12985d3.png)

This is not handled properly by the client: the freezing backend is unexpected. More so, this corrupted backend state should never be reached, i.e. by limiting the successive requests (within a certain amount of time) that are being send to API endpoints. A dedicated service for this functionality is already in existence (lizard-http-throttler), but that only throttles specific requests, and currently doesn't filter out enough requests.

**Comment by gijs** [comment]
@ernstkui and I discussed this issue and want to investigate if this bug may exist only when running a devserver using Grunt (`grunt serve`) with a local proxy. 

Perhaps that proxy isnt the most stable piece of engineering around. Evidence for this may be the fact that the Django devserver doesnt actually crash but something in the middle seems to hang: the proxy?

**Comment by lexvand** [comment]
Out of date
