### ISSUE TITLE
[Weak wish] Enable the selected layer when adding it from the layer catalog

### ISSUE THREAD

**Issue by gijs** [nens/lizard-client#759]
If the user searches the catalog for a layer, we can assume that he/she has the intent of viewing/interacting with that layer. 
Currently, the user has to add the layer, then enable it. 

**A useful enhancement would be to automatically enable the added layer(s).**

**Comment by lexvand** [comment]
Is fixed

**Comment by gijs** [comment]
Thanks man! 😄
